[2018-07-04 06:54:12 +0200] [4289] [DEBUG] Current configuration:
  suppress_ragged_eofs: True
  backlog: 2048
  when_ready: <function WhenReady.when_ready at 0x7feedbac8268>
  check_config: False
  accesslog: None
  enable_stdio_inheritance: False
  statsd_prefix: 
  keyfile: None
  on_starting: <function OnStarting.on_starting at 0x7feedbab9ea0>
  post_fork: <function Postfork.post_fork at 0x7feedbac8598>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7feedbac8730>
  pre_exec: <function PreExec.pre_exec at 0x7feedbac8bf8>
  limit_request_line: 4094
  child_exit: <function ChildExit.child_exit at 0x7feedbacd0d0>
  worker_exit: <function WorkerExit.worker_exit at 0x7feedbacd268>
  capture_output: False
  certfile: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  statsd_host: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-SSL': 'on', 'X-FORWARDED-PROTO': 'https'}
  proxy_protocol: False
  cert_reqs: 0
  reload: False
  sendfile: None
  daemon: False
  umask: 0
  do_handshake_on_connect: False
  syslog: False
  reload_engine: auto
  graceful_timeout: 30
  logger_class: gunicorn.glogging.Logger
  keepalive: 2
  default_proc_name: Server:application
  tmp_upload_dir: None
  limit_request_field_size: 8190
  pre_fork: <function Prefork.pre_fork at 0x7feedbac8400>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7feedbacd400>
  worker_class: eventlet
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function PreRequest.pre_request at 0x7feedbac8d90>
  pythonpath: None
  logconfig: None
  user: 0
  spew: False
  max_requests_jitter: 0
  raw_paste_global_conf: []
  syslog_facility: user
  ssl_version: 2
  errorlog: /home/nicola/Documenti/Lavoro/UnionService/Server/log/gunicorn.log
  group: 0
  loglevel: debug
  chdir: /home/nicola/Documenti/Lavoro/UnionService/Server
  config: None
  initgroups: False
  on_reload: <function OnReload.on_reload at 0x7feedbac80d0>
  worker_connections: 1000
  preload_app: False
  workers: 1
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  ciphers: TLSv1
  timeout: 30
  limit_request_fields: 100
  forwarded_allow_ips: ['127.0.0.1']
  post_request: <function PostRequest.post_request at 0x7feedbac8ea0>
  raw_env: []
  paste: None
  max_requests: 0
  proc_name: None
  worker_tmp_dir: None
  threads: 1
  on_exit: <function OnExit.on_exit at 0x7feedbacd598>
  pidfile: /var/run/gunicorn.pid
  worker_int: <function WorkerInt.worker_int at 0x7feedbac88c8>
  worker_abort: <function WorkerAbort.worker_abort at 0x7feedbac8a60>
  bind: ['127.0.0.1:3000']
  ca_certs: None
[2018-07-04 06:54:12 +0200] [4289] [INFO] Starting gunicorn 19.7.1
[2018-07-04 06:54:13 +0200] [4385] [DEBUG] Current configuration:
  enable_stdio_inheritance: False
  preload_app: False
  worker_tmp_dir: None
  on_reload: <function OnReload.on_reload at 0x7f68f7a070d0>
  when_ready: <function WhenReady.when_ready at 0x7f68f7a07268>
  on_exit: <function OnExit.on_exit at 0x7f68f7a0c598>
  suppress_ragged_eofs: True
  bind: ['127.0.0.1:3000']
  reload_engine: auto
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/nicola/Documenti/Lavoro/UnionService/Server/log/gunicorn.log
  threads: 1
  max_requests: 0
  logger_class: gunicorn.glogging.Logger
  worker_connections: 1000
  post_fork: <function Postfork.post_fork at 0x7f68f7a07598>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f68f7a07a60>
  daemon: False
  raw_env: []
  cert_reqs: 0
  logconfig: None
  syslog: False
  chdir: /home/nicola/Documenti/Lavoro/UnionService/Server
  forwarded_allow_ips: ['127.0.0.1']
  max_requests_jitter: 0
  loglevel: debug
  config: None
  pythonpath: None
  default_proc_name: Server:application
  capture_output: False
  graceful_timeout: 30
  keyfile: None
  ssl_version: 2
  ciphers: TLSv1
  syslog_prefix: None
  syslog_facility: user
  proxy_protocol: False
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f68f7a0c400>
  ca_certs: None
  pre_request: <function PreRequest.pre_request at 0x7f68f7a07d90>
  worker_exit: <function WorkerExit.worker_exit at 0x7f68f7a0c268>
  paste: None
  statsd_prefix: 
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f68f7a07730>
  statsd_host: None
  group: 0
  keepalive: 2
  proc_name: None
  certfile: None
  umask: 0
  initgroups: False
  secure_scheme_headers: {'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-SSL': 'on'}
  on_starting: <function OnStarting.on_starting at 0x7f68f79f8ea0>
  child_exit: <function ChildExit.child_exit at 0x7f68f7a0c0d0>
  reload: False
  proxy_allow_ips: ['127.0.0.1']
  check_config: False
  accesslog: None
  worker_int: <function WorkerInt.worker_int at 0x7f68f7a078c8>
  pidfile: /var/run/gunicorn.pid
  user: 0
  tmp_upload_dir: None
  raw_paste_global_conf: []
  syslog_addr: udp://localhost:514
  do_handshake_on_connect: False
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  backlog: 2048
  workers: 1
  timeout: 30
  pre_fork: <function Prefork.pre_fork at 0x7f68f7a07400>
  spew: False
  pre_exec: <function PreExec.pre_exec at 0x7f68f7a07bf8>
  sendfile: None
  post_request: <function PostRequest.post_request at 0x7f68f7a07ea0>
  worker_class: eventlet
[2018-07-04 06:54:13 +0200] [4385] [INFO] Starting gunicorn 19.7.1
[2018-07-04 06:54:14 +0200] [4481] [DEBUG] Current configuration:
  enable_stdio_inheritance: False
  spew: False
  syslog_facility: user
  pre_exec: <function PreExec.pre_exec at 0x7f9630abebf8>
  raw_paste_global_conf: []
  ssl_version: 2
  child_exit: <function ChildExit.child_exit at 0x7f9630ac30d0>
  bind: ['127.0.0.1:3000']
  cert_reqs: 0
  syslog_addr: udp://localhost:514
  max_requests: 0
  max_requests_jitter: 0
  default_proc_name: Server:application
  reload_engine: auto
  daemon: False
  paste: None
  limit_request_field_size: 8190
  pidfile: /var/run/gunicorn.pid
  pre_fork: <function Prefork.pre_fork at 0x7f9630abe400>
  statsd_host: None
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f9630abe730>
  worker_tmp_dir: None
  group: 0
  do_handshake_on_connect: False
  umask: 0
  check_config: False
  threads: 1
  graceful_timeout: 30
  accesslog: None
  syslog_prefix: None
  statsd_prefix: 
  worker_abort: <function WorkerAbort.worker_abort at 0x7f9630abea60>
  keyfile: None
  initgroups: False
  post_fork: <function Postfork.post_fork at 0x7f9630abe598>
  ca_certs: None
  worker_int: <function WorkerInt.worker_int at 0x7f9630abe8c8>
  raw_env: []
  tmp_upload_dir: None
  logconfig: None
  timeout: 30
  worker_exit: <function WorkerExit.worker_exit at 0x7f9630ac3268>
  worker_connections: 1000
  forwarded_allow_ips: ['127.0.0.1']
  proxy_allow_ips: ['127.0.0.1']
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  ciphers: TLSv1
  config: None
  worker_class: eventlet
  reload: False
  backlog: 2048
  user: 0
  proc_name: None
  preload_app: False
  sendfile: None
  secure_scheme_headers: {'X-FORWARDED-SSL': 'on', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-PROTOCOL': 'ssl'}
  errorlog: /home/nicola/Documenti/Lavoro/UnionService/Server/log/gunicorn.log
  when_ready: <function WhenReady.when_ready at 0x7f9630abe268>
  keepalive: 2
  limit_request_fields: 100
  chdir: /home/nicola/Documenti/Lavoro/UnionService/Server
  pythonpath: None
  loglevel: debug
  logger_class: gunicorn.glogging.Logger
  on_reload: <function OnReload.on_reload at 0x7f9630abe0d0>
  post_request: <function PostRequest.post_request at 0x7f9630abeea0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f9630ac3400>
  on_exit: <function OnExit.on_exit at 0x7f9630ac3598>
  certfile: None
  workers: 1
  syslog: False
  on_starting: <function OnStarting.on_starting at 0x7f9630aafea0>
  pre_request: <function PreRequest.pre_request at 0x7f9630abed90>
  suppress_ragged_eofs: True
  limit_request_line: 4094
  capture_output: False
  proxy_protocol: False
[2018-07-04 06:54:14 +0200] [4481] [INFO] Starting gunicorn 19.7.1
[2018-07-04 06:54:14 +0200] [4481] [DEBUG] Arbiter booted
[2018-07-04 06:54:14 +0200] [4481] [INFO] Listening at: http://127.0.0.1:3000 (4481)
[2018-07-04 06:54:14 +0200] [4481] [INFO] Using worker: eventlet
[2018-07-04 06:54:14 +0200] [4484] [INFO] Booting worker with pid: 4484
[2018-07-04 06:54:14 +0200] [4481] [DEBUG] 1 workers
[2018-07-04 06:54:19 +0200] [4484] [DEBUG] GET /prezzarioProdotti
[2018-07-04 06:54:19 +0200] [4484] [ERROR] Exception on /prezzarioProdotti [GET]
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: ERRORE:  la colonna modello_prodotto_prezzario.capitolato non esiste
LINE 1: ...ipologia AS modello_prodotto_prezzario_tipologia, modello_pr...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/nicola/Documenti/Lavoro/UnionService/Server/app/controller.py", line 64, in prezzarioProdotti
    modelli = ModelloProdotto.query.all()
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return list(self)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
    return self._execute_and_instances(context)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2948, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) ERRORE:  la colonna modello_prodotto_prezzario.capitolato non esiste
LINE 1: ...ipologia AS modello_prodotto_prezzario_tipologia, modello_pr...
                                                             ^
 [SQL: 'SELECT modello_prodotto_prezzario.nome AS modello_prodotto_prezzario_nome, modello_prodotto_prezzario.tipologia AS modello_prodotto_prezzario_tipologia, modello_prodotto_prezzario.capitolato AS modello_prodotto_prezzario_capitolato \nFROM modello_prodotto_prezzario'] (Background on this error at: http://sqlalche.me/e/f405)
[2018-07-04 06:54:19 +0200] [4484] [DEBUG] Closing connection. 
[2018-07-04 06:55:59 +0200] [4484] [DEBUG] GET /prezzarioProdotti
[2018-07-04 06:55:59 +0200] [4484] [DEBUG] Closing connection. 
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] GET /socket.io/
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] Closing connection. 
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] GET /getNotifiche
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] GET /sidebarLeft
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] GET /header
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] Closing connection. 
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] Closing connection. 
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] Closing connection. 
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] POST /socket.io/
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] Closing connection. 
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] GET /socket.io/
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] Closing connection. 
[2018-07-04 06:56:00 +0200] [4484] [DEBUG] GET /socket.io/
[2018-07-04 06:56:01 +0200] [4484] [DEBUG] POST /socket.io/
[2018-07-04 06:56:01 +0200] [4484] [DEBUG] Closing connection. 
[2018-07-04 06:56:01 +0200] [4484] [DEBUG] GET /socket.io/
[2018-07-04 06:56:01 +0200] [4484] [DEBUG] Closing connection. 
[2018-07-04 06:56:01 +0200] [4484] [DEBUG] GET /homepage
[2018-07-04 06:56:01 +0200] [4484] [DEBUG] Closing connection. 
